testing cd

diff --git a/.github/workflows/k8s-cicd.yaml b/.github/workflows/k8s-cicd.yaml
--- a/.github/workflows/k8s-cicd.yaml
+++ b/.github/workflows/k8s-cicd.yaml
@@ -10,7 +10,7 @@ env:
   DOCKER_USERNAME: pisethmao
   DOCKER_IMAGE_NAME: real-devops-website
   IMAGE_TAG: ${{ github.sha }}
-  HELM_REPOSITORY: git@github.com:PisethMao/deploy-project-with-argocd.git
+  HELM_REPOSITORY: https://github.com/PisethMao/deploy-project-with-argocd.git
 jobs:
   ci-job:
     runs-on: ubuntu-latest
@@ -49,6 +49,49 @@ jobs:
       - name: Logout From Dockerhub
         if: github.event_name == 'push'
         run: docker logout
+  # cd-job:
+  #   needs: ci-job
+  #   runs-on: ubuntu-latest
+  #   environment: HELM_ENV
+  #   steps:
+  #     - name: Install YQ
+  #       run: |
+  #         sudo wget https://github.com/mikefarah/yq/releases/download/v4.44.1/yq_linux_amd64 -O /usr/local/bin/yq
+  #         sudo chmod +x /usr/local/bin/yq
+  #         yq --version
+  #     - name: Add Commit SHA To ENV
+  #       run: |
+  #         echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
+  #     # - name: Setup SSH
+  #     #   run: |
+  #     #     mkdir -p ~/.ssh
+  #     #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
+  #     #     chmod 600 ~/.ssh/id_ed25519
+  #     #     ssh-keyscan github.com >> ~/.ssh/known_hosts
+  #     - name: Clone ArgoCD Repository
+  #       run: |
+  #         git clone https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/PisethMao/deploy-project-with-argocd.git argocd-repo
+  #     - name: Update Helm Chart
+  #       run: |
+  #         cd argocd-repo
+  #         yq e '.image.repository = "'$DOCKER_USERNAME'/'$DOCKER_IMAGE_NAME'"' -i helm/values.yaml
+  #         yq e '.image.tag = "'$IMAGE_TAG'"' -i helm/values.yaml
+  #     - name: Update Kubernetes Deployment Image
+  #       run: |
+  #         cd argocd-repo
+  #         yq e '.spec.template.spec.containers[0].image = "'$DOCKER_USERNAME'/'$DOCKER_IMAGE_NAME':'$IMAGE_TAG'"' -i k8s/deployment.yaml
+  #     - name: Commit and Push Changes
+  #       run: |
+  #         cd argocd-repo
+  #         git config user.name "github-actions"
+  #         git config user.email "github-actions@github.com"
+  #         git add .
+  #         git commit -m "Update image to $IMAGE_TAG" || echo "No changes"
+  #         git push
+  #     - name: Clean Up
+  #       run: |
+  #         rm -rf ~/.ssh
+  #         rm -rf argocd-repo
   cd-job:
     needs: ci-job
     runs-on: ubuntu-latest
@@ -60,17 +103,10 @@ jobs:
           sudo chmod +x /usr/local/bin/yq
           yq --version
       - name: Add Commit SHA To ENV
-        run: |
-          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
-      - name: Setup SSH
-        run: |
-          mkdir -p ~/.ssh
-          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
-          chmod 600 ~/.ssh/id_ed25519
-          ssh-keyscan github.com >> ~/.ssh/known_hosts
+        run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
       - name: Clone ArgoCD Repository
         run: |
-          git clone $HELM_REPOSITORY argocd-repo
+          git clone https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/PisethMao/deploy-project-with-argocd.git argocd-repo
       - name: Update Helm Chart
         run: |
           cd argocd-repo
@@ -88,7 +124,3 @@ jobs:
           git add .
           git commit -m "Update image to $IMAGE_TAG" || echo "No changes"
           git push
-      - name: Clean Up
-        run: |
-          rm -rf ~/.ssh
-          rm -rf argocd-repo
